#!/usr/bin/env python
#
# LRMS UR Generator executable.
#
# Module for the LRMS UR Generator module.
#
# Author: Henrik Thostrup Jensen <htj@ndgf.org>
# Copyright: Nordic Data Grid Facility (2009)

import sys

from lrmsurgen import config



def main():

    parser = config.getParser()
    options, args = parser.parse_args()
    cfg = config.getConfig(options.config)

    hostname = config.getConfigValue(cfg, 'common', 'hostname')
    if hostname is None:
        import socket
        hostname = socket.getfqdn()

    usermap_file = config.getConfigValue(cfg, 'common', 'usermap', config.DEFAULT_USERMAP_FILE)

    try:
        usermap = config.getUserMap(usermap_file)
    except IOError:
        print 'IOError while attempting to read usermap (missing file)'
        sys.exit(2)
        return

    sections = cfg.sections()
    if 'maui' in sections:
        from lrmsurgen import maui as lrms
    # more to come...

    lrms.generateUsageRecords(cfg, hostname, usermap)


if __name__ == '__main__':
    main()

